# Generated by Django 4.2.2 on 2023-06-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='in_inicio',
            new_name='in_home',
        ),
    ]
