# Generated by Django 4.1.7 on 2023-08-12 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre corto'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resume',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen'),
        ),
    ]
