# Generated by Django 4.2.3 on 2023-08-31 21:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_alter_category_name_alter_category_short_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='Titulo')),
                ('public', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='Instagram', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Imagen Instagram',
                'verbose_name_plural': 'Imagenes Instagram',
            },
        ),
    ]
