# Generated by Django 4.2.3 on 2023-08-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='image',
        ),
        migrations.AddField(
            model_name='instagram',
            name='image1',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 1'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image2',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image3',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 3'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image4',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 4'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image5',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 5'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image6',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 6'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image7',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 7 '),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image8',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 8'),
        ),
        migrations.AddField(
            model_name='instagram',
            name='image9',
            field=models.ImageField(null=True, upload_to='Instagram', verbose_name='Imagen 9'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
